/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.primus.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Patient service. Represents a row in the &quot;Primus_Patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.primus.model.impl.PatientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.primus.model.impl.PatientImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a patient model instance should use the {@link Patient} interface instead.
 * </p>
 *
 * @author Juan Fernández
 * @see Patient
 * @see com.primus.model.impl.PatientImpl
 * @see com.primus.model.impl.PatientModelImpl
 * @generated
 */
public interface PatientModel extends BaseModel<Patient> {
	/**
	 * Gets the primary key of this patient.
	 *
	 * @return the primary key of this patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patient
	 *
	 * @param pk the primary key of this patient
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the patient id of this patient.
	 *
	 * @return the patient id of this patient
	 */
	public long getPatientId();

	/**
	 * Sets the patient id of this patient.
	 *
	 * @param patientId the patient id of this patient
	 */
	public void setPatientId(long patientId);

	/**
	 * Gets the company id of this patient.
	 *
	 * @return the company id of this patient
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this patient.
	 *
	 * @param companyId the company id of this patient
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this patient.
	 *
	 * @return the group id of this patient
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this patient.
	 *
	 * @param groupId the group id of this patient
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the creator user id of this patient.
	 *
	 * @return the creator user id of this patient
	 */
	public long getCreatorUserId();

	/**
	 * Sets the creator user id of this patient.
	 *
	 * @param creatorUserId the creator user id of this patient
	 */
	public void setCreatorUserId(long creatorUserId);

	/**
	 * Gets the creator user uuid of this patient.
	 *
	 * @return the creator user uuid of this patient
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreatorUserUuid() throws SystemException;

	/**
	 * Sets the creator user uuid of this patient.
	 *
	 * @param creatorUserUuid the creator user uuid of this patient
	 */
	public void setCreatorUserUuid(String creatorUserUuid);

	/**
	 * Gets the create date of this patient.
	 *
	 * @return the create date of this patient
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this patient.
	 *
	 * @param createDate the create date of this patient
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this patient.
	 *
	 * @return the modified date of this patient
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this patient.
	 *
	 * @param modifiedDate the modified date of this patient
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the name of this patient.
	 *
	 * @return the name of this patient
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this patient.
	 *
	 * @param name the name of this patient
	 */
	public void setName(String name);

	/**
	 * Gets the surname1 of this patient.
	 *
	 * @return the surname1 of this patient
	 */
	@AutoEscape
	public String getSurname1();

	/**
	 * Sets the surname1 of this patient.
	 *
	 * @param surname1 the surname1 of this patient
	 */
	public void setSurname1(String surname1);

	/**
	 * Gets the surname2 of this patient.
	 *
	 * @return the surname2 of this patient
	 */
	@AutoEscape
	public String getSurname2();

	/**
	 * Sets the surname2 of this patient.
	 *
	 * @param surname2 the surname2 of this patient
	 */
	public void setSurname2(String surname2);

	/**
	 * Gets the id of this patient.
	 *
	 * @return the id of this patient
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the id of this patient.
	 *
	 * @param id the id of this patient
	 */
	public void setId(String id);

	/**
	 * Gets the birth date of this patient.
	 *
	 * @return the birth date of this patient
	 */
	public Date getBirthDate();

	/**
	 * Sets the birth date of this patient.
	 *
	 * @param birthDate the birth date of this patient
	 */
	public void setBirthDate(Date birthDate);

	/**
	 * Gets a copy of this patient as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Patient toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Patient patient);

	public int hashCode();

	public String toString();

	public String toXmlString();
}